version: '2'
services:
  web:
    build: .
    command: bundle exec jekyll serve
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    volumes_from:
      - bundle
  bundle:
    image: jekyllondocker_web
    command: echo bundler container
    volumes:
      - /bundle
